In [1]:
import numpy as np

def solve_linear_equation(A, b):
  #TODO:
  # enter your code here, and remove the following line (30%)
  rank_a = np.linalg.matrix_rank(A)
  matrix_ab = np.hstack([A, b])
  rank_ab = np.linalg.matrix_rank(matrix_ab)
  if rank_a == rank_ab:
    # consistent, at least one sol
    n = A.shape[1]
    if rank_a == n:
      # rank a = n, at most one sol
      return 1
    else:
      return 0
  else:
    # no sol
    return -1

def flag_to_message(flag):
   if flag == 1:
     print('The linear system Ax=b has only one solution.')
   elif flag == 0:
     print('The linear system Ax=b has infinitely many solutions.')
   elif flag == -1:
     print('The linear system Ax=b has no solutions.')
   else:
     print('Unknown flag!')

def get_input_data(input_id):
   if input_id == 'case1': 
     A = np.array([[3, 2, -1], [6, -1, 3], [1, 10, -2]])
     b = np.array([[-7], [-4], [2]])
   elif input_id == 'case2':
     A = np.array([[4, -1, 3], [21, -4, 18], [-9, 1, -9]])
     b = np.array([[5], [7], [-8]])
   elif input_id == 'case3':
     A = np.array([[7, -4, 1], [3, 2, -1], [5, 12, -5]])
     b = np.array([[-15], [-5], [-5]])
   return A, b

if __name__ == '__main__':
   for case in ['case1', 'case2', 'case3']:
     A, b = get_input_data(case)
     print(case)
     print('A =', A, 'b =', b.T)
     flag = solve_linear_equation(A, b)
     flag_to_message(flag)
     if flag == 1:
       print('The solution is ', np.linalg.solve(A, b))
     print()


case1
A = [[ 3  2 -1]
 [ 6 -1  3]
 [ 1 10 -2]] b = [[-7 -4  2]]
The linear system Ax=b has only one solution.
The solution is  [[-2.]
 [ 1.]
 [ 3.]]

case2
A = [[ 4 -1  3]
 [21 -4 18]
 [-9  1 -9]] b = [[ 5  7 -8]]
The linear system Ax=b has no solutions.

case3
A = [[ 7 -4  1]
 [ 3  2 -1]
 [ 5 12 -5]] b = [[-15  -5  -5]]
The linear system Ax=b has infinitely many solutions.



## Q1
can we use `np.linalg.solve()` to determine whether $Ax=b$ is consistent. Explain the reason (5%)

## Q1 Ans

No, we cannot use `np.linalg.solve()` to determine $Ax=b$ is consistent or not. 
With $Ax = b$ consistent, the linear equation can be either one solution or infinite number of solution. However, `np.linalg.solve()` can only handled single solution problem. Hense, the linear equation with multiple solution will cause the error raised.

## Q2

Given matrix $A$ of dimension (m,n). If $rank(A) = n$, can we infer that $Ax=b$ is consistent? Expalin (5%)

## Q2 Ans

Yes, if the rank of the coefficient matrix A is equal to the number of columns (n), then the linear system Ax = b is consistent for any constant vector b in R^m.

if the rank(A)=n, it means that the columns of A are linearly independent, and the matrix has full column rank. Therefore, every column of A can be expressed as a linear combination of the other columns. so if rank(A) = n, then the linear equation is consistent for any constant vector $b\in  R^m$